EMOJI_MAPPINGS = {
    "peepoNotes": "I am thinking.",
    "Bedge": "I am sleepy.",
    "wokege": "I am not sleepy.",
    "YEPP": "I am indifferent.",
    "Sadge": "I am sad.",
    "Madge": "I am mad!",
    "s2jFEELS": "I am very sad.",
    "Okayge": "Okay.",
    "strim": "I want a stream.",
    "peepoLove": "I love it!",
    "peepoSad": "I am extremely sad...",
    "Prayge": "I am hopeful!",
    "pepeHMM": "Hmmm....",
    "Susge": "I am suspicious...",
    "COPIUM": "I'm pretty sad and not hopeful.",
    "Smadge": "I'm both sad and angry!",
    "PikaFacepalm": "Ugh..",
    "HYPERS": "I am very excited!",
    "monkaS": "I'm very scared...",
    "monkaW": "I'm very very very scared!!",
    "ResidentPOGGER": "This is extremely boring.",
    "POGGERS": "THIS IS AMAZING!",
    "Gladge": "I am doing well.",
    "POGPLANT": "VERY COOL!",
    "PepeHands": "I am so sad right now.",
    "Pepega": "You are dumb.",
    "Pepepains": "This hurts to watch."
}
